version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.4.0
    
    working_directory: ~/server
    
    steps:
      - checkout
      - run: node --version     

      - run: yarn install

      - run: yarn test 
