version: 2
jobs:
  build:
    docker:
      - image: node:alpine
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: simonpiquet
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: stripe-db
      - image: redis:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd server && yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}

      # run tests!
      - run: cd server yarn ci:test

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            apt-get update
            apt-get install curl
            curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz \
            && tar xzvf docker-17.04.0-ce.tgz \
            && mv docker/docker /usr/local/bin \
            && rm -r docker docker-17.04.0-ce.tgz
      - run: cd server && yarn ci:docker
