# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1


steps:
  - checkout

  - run: yarn install


  # Run tests
  - run: yarn test


