version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.4.0
    
    working_directory: ~/repo
    
    steps:
      - checkout
      - run: node --version     

  test:
    docker:
      - image: cimg/node:17.4.0
      
    steps:
      - checkout
      - run: cd server && yarn install 
      - run: yarn test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build