version: 2
jobs:
  build:
    docker:
      - image: node:alpine
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: POSTGRES_USER
          POSTGRES_PASSWORD: POSTGRES_PASSWORD
          POSTGRES_DB: POSTGRES_DB
      - image: redis:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd server && yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}

      # run tests!
      - run: cd server yarn ci:test

      - setup_remote_docker:
          docker_layer_caching: true

        # Install via apk on alpine based images
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run: cd server && yarn ci:docker
