version: "3.7"
services:
  redis:
    image: redis
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
  web:
    image: stripe-project-multi-stage
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
